--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "USERNAME"."MSGS" (
		"ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"USER_ID" INTEGER NOT NULL,
		"USER_TO" INTEGER NOT NULL,
		"CONTENT" VARCHAR(2000),
		"IS_READN" INTEGER DEFAULT 0 NOT NULL,
		"TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE "USERNAME"."LIKES" (
		"USER_ID" INTEGER NOT NULL,
		"EBOOK_ID" INTEGER NOT NULL
	);

CREATE TABLE "USERNAME"."USERS" (
		"ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"USERNAME" VARCHAR(10) NOT NULL,
		"EMAIL" VARCHAR(500) NOT NULL,
		"PASSWORD" VARCHAR(8) NOT NULL,
		"FULLNAME" VARCHAR(255) NOT NULL,
		"STREET" VARCHAR(255) NOT NULL,
		"STREET_NUMBER" INTEGER NOT NULL,
		"CITY" VARCHAR(255) NOT NULL,
		"ZIP" VARCHAR(7) NOT NULL,
		"TELEPHONE" VARCHAR(255) NOT NULL,
		"NICKNAME" VARCHAR(20) NOT NULL,
		"BIO" VARCHAR(50),
		"PHOTO" VARCHAR(1000),
		"IS_ADMIN" INTEGER DEFAULT 0 NOT NULL,
		"TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE "USERNAME"."READINGS" (
		"USER_ID" INTEGER NOT NULL,
		"EBOOK_ID" INTEGER NOT NULL,
		"POSITION" VARCHAR(1000)
	);

CREATE TABLE "USERNAME"."REVIEWS" (
		"ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"USER_ID" INTEGER NOT NULL,
		"EBOOK_ID" INTEGER NOT NULL,
		"CONTENT" VARCHAR(20000) NOT NULL,
		"IS_PUBLISHED" INTEGER DEFAULT 0 NOT NULL,
		"TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE "USERNAME"."EBOOKS" (
		"ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"NAME" VARCHAR(500) NOT NULL,
		"PATH" VARCHAR(2000) NOT NULL,
		"PRICE" VARCHAR(5) NOT NULL,
		"DESCRIPTION" VARCHAR(20000) NOT NULL,
		"TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE TABLE "USERNAME"."PURCHASES" (
		"USER_ID" INTEGER NOT NULL,
		"EBOOK_ID" INTEGER NOT NULL,
		"TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	);

CREATE INDEX "USERNAME"."SQL180226090138280" ON "USERNAME"."PURCHASES" ("USER_ID" ASC);

CREATE UNIQUE INDEX "USERNAME"."SQL180226090138140" ON "USERNAME"."USERS" ("USERNAME" ASC);

CREATE INDEX "USERNAME"."SQL180226090138251" ON "USERNAME"."REVIEWS" ("USER_ID" ASC);

CREATE UNIQUE INDEX "USERNAME"."SQL180226090138120" ON "USERNAME"."USERS" ("ID" ASC);

CREATE UNIQUE INDEX "USERNAME"."SQL180226090138170" ON "USERNAME"."EBOOKS" ("ID" ASC);

CREATE UNIQUE INDEX "USERNAME"."SQL180226090138310" ON "USERNAME"."READINGS" ("USER_ID" ASC, "EBOOK_ID" ASC);

CREATE INDEX "USERNAME"."SQL180226090138202" ON "USERNAME"."LIKES" ("EBOOK_ID" ASC);

CREATE INDEX "USERNAME"."SQL180226090138312" ON "USERNAME"."READINGS" ("EBOOK_ID" ASC);

CREATE UNIQUE INDEX "USERNAME"."SQL180226090138200" ON "USERNAME"."LIKES" ("USER_ID" ASC, "EBOOK_ID" ASC);

CREATE UNIQUE INDEX "USERNAME"."SQL180226090138250" ON "USERNAME"."REVIEWS" ("ID" ASC);

CREATE INDEX "USERNAME"."SQL180226090138380" ON "USERNAME"."MSGS" ("USER_ID" ASC);

CREATE UNIQUE INDEX "USERNAME"."SQL180226090138370" ON "USERNAME"."MSGS" ("ID" ASC);

CREATE INDEX "USERNAME"."SQL180226090138281" ON "USERNAME"."PURCHASES" ("EBOOK_ID" ASC);

CREATE INDEX "USERNAME"."SQL180226090138311" ON "USERNAME"."READINGS" ("USER_ID" ASC);

CREATE INDEX "USERNAME"."SQL180226090138381" ON "USERNAME"."MSGS" ("USER_TO" ASC);

CREATE INDEX "USERNAME"."SQL180226090138201" ON "USERNAME"."LIKES" ("USER_ID" ASC);

CREATE INDEX "USERNAME"."SQL180226090138252" ON "USERNAME"."REVIEWS" ("EBOOK_ID" ASC);

ALTER TABLE "USERNAME"."EBOOKS" ADD CONSTRAINT "SQL180226090138170" PRIMARY KEY ("ID");

ALTER TABLE "USERNAME"."MSGS" ADD CONSTRAINT "SQL180226090138370" PRIMARY KEY ("ID");

ALTER TABLE "USERNAME"."READINGS" ADD CONSTRAINT "READINGS_PRIMARY_KEY" PRIMARY KEY ("USER_ID", "EBOOK_ID");

ALTER TABLE "USERNAME"."LIKES" ADD CONSTRAINT "PRIMARY_KEY" PRIMARY KEY ("USER_ID", "EBOOK_ID");

ALTER TABLE "USERNAME"."USERS" ADD CONSTRAINT "SQL180226090138120" PRIMARY KEY ("ID");

ALTER TABLE "USERNAME"."REVIEWS" ADD CONSTRAINT "SQL180226090138250" PRIMARY KEY ("ID");

ALTER TABLE "USERNAME"."REVIEWS" ADD CONSTRAINT "REVIEWS_USER_REF" FOREIGN KEY ("USER_ID")
	REFERENCES "USERNAME"."USERS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."READINGS" ADD CONSTRAINT "READINGS_EBOOK_REF" FOREIGN KEY ("EBOOK_ID")
	REFERENCES "USERNAME"."EBOOKS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."LIKES" ADD CONSTRAINT "LIKES_USER_REF" FOREIGN KEY ("USER_ID")
	REFERENCES "USERNAME"."USERS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."MSGS" ADD CONSTRAINT "FROMREF" FOREIGN KEY ("USER_ID")
	REFERENCES "USERNAME"."USERS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."PURCHASES" ADD CONSTRAINT "PURCHASES_USER_REF" FOREIGN KEY ("USER_ID")
	REFERENCES "USERNAME"."USERS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."REVIEWS" ADD CONSTRAINT "REVIEWS_EBOOK_REF" FOREIGN KEY ("EBOOK_ID")
	REFERENCES "USERNAME"."EBOOKS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."READINGS" ADD CONSTRAINT "READINGS_USER_REF" FOREIGN KEY ("USER_ID")
	REFERENCES "USERNAME"."USERS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."MSGS" ADD CONSTRAINT "TOREF" FOREIGN KEY ("USER_TO")
	REFERENCES "USERNAME"."USERS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."PURCHASES" ADD CONSTRAINT "PURCHASES_EBOOK_REF" FOREIGN KEY ("EBOOK_ID")
	REFERENCES "USERNAME"."EBOOKS" ("ID")
	ON DELETE CASCADE;

ALTER TABLE "USERNAME"."LIKES" ADD CONSTRAINT "LIKES_EBOOK_REF" FOREIGN KEY ("EBOOK_ID")
	REFERENCES "USERNAME"."EBOOKS" ("ID")
	ON DELETE CASCADE;

